### PR TITLE
Add protobuf and zlib; enable windows auto build

### PR DESCRIPTION
**Pull request by thanhdowisc**
Hi Folks,

This pull request is a first step to enable Windows CI. I made following changes:
- add zlib and protobuf in libs
- change CMakeLists.txt to compile zlib and protobuf in Windows.

With this changes, C++ branch build successfully in Visual Studio 2013 because it supports C++11. However, the build broke in Visual Studio 2010 which only supports C++9.

The next step would be set up a build server. I've tested with appveyor and it works. I am not sure how a webhook can be added for this CI though.

Thanks.

### CODE REVIEW

**Comment by thanhdowisc** [comment]
Hi Owen, could you please take a look and see if it is ready to merge? Then I will change appveyor settings and provide you and URL for webhook. Thanks!

**Comment by thanhdowisc** [comment]
Hi Owen,

Could you please take a look at this? We have strong interest in getting this in ASAP since we are working with this library internally. We really want some thing that is stable for our dev environment.

Thanks,
Thanh

**Comment by omalley** [comment]
I'll look at it now. My plan is to use the bundled version of zlib, protobuf, and snappy for all of the platforms instead of just windows.

**Comment by thanhdowisc** [comment]
Thank you, Owen.

Here is the webhook for AppVeyor in case you haven't got it.
https://ci.appveyor.com/api/github/webhook?id=pqcqker37ddy20s7

One more thing, Owen, I am not sure about my privilege with the code base. I am working on building a prototype system that uses native ORC and may need to change ORC code. Could you please let me know what would be the correct way to do so?

**Pull request closed without merging**
