### PR TITLE
Changes to make orc lib compile in windows.

### PR DESCRIPTION
**Pull request by thanhdowisc**
Hi Folks. 

This change is to make native orc compile in Windows Visual Studio 2010. It contains:

- changes to CMakeLists file so that cmake now can generate a solution file for visual studio
- revert some C++11 features to make the library compile in VS10
  + e.g., default and delete keywords
  + for each
- add parenthesis around std::min/max to avoid conflict with windows predefined macros.

### CODE REVIEW

**Comment by omalley** [comment]
This change broke Linux and Mac, but I've pushed an update of your patch to the vs10 branch. Please try it on Windows and see if the vs10 branch works on Windows. 

Long term it would be great if Microsoft could set up a CI build from this repository so that we knew if things were breaking on Windows.

**Comment by thanhdowisc** [comment]
vs10 broke on Windows, and the only root cause is that the std::min function requires its argument to have the same types explicitly. Hence we have to use appropriate static_cast.

Should I make another pull request to the vs10 branch in hortonworks/orc?

**Comment by owen-orc** [comment]
Since vs10 is just a dev branch, you can just commit to it.

Thanks,
   Owen

**Comment by thanhdowisc** [comment]
awesome, i can just do a push then. Thanks!

**Comment by thanhdowisc** [comment]
Hi Owen, I tried to do a "git push origin vs10" but got a permission denied. Could you please check my permission on vs10?

Thanks.

**Comment by owen-orc** [comment]
I've invited you (thanhdowisc) to the msft-orc-team, which would give you
write permissions.  You need to accept joining the group though.

**Comment by thanhdowisc** [comment]
Hi Owen. I've seen an invitation so far. Is this supposed to be in the email associated with my account (thanhdowisc)?

**Comment by owen-orc** [comment]
I cancelled the invite and resent it. If you don't get email, try logging
into github and clicking on your notifications.

Thanks,
   Owen

**Comment by thanhdowisc** [comment]
This time it works. Thank you!

**Comment by thanhdowisc** [comment]
Hi Owen, 

As more and more code are getting committed to the main branch, I want to set up an CI build for Windows as you mention sooner than later. Since this is the first time I work on Github, could you point me to some sources that can help me do that.

Thanks,
Thanh

**Comment by owen-orc** [comment]
Thanh,
  It looks like travis-ci, which does the linux builds, does not support
Windows. If you look at the travis-ci page
https://travis-ci.org/hortonworks/orc you can see the previous builds. If
you look at the .travis.yml file, you can see the
commands it is using. Fundamentally, you'd need to have a CI infrastructure
that was getting notified by github when a
commit happens.

Thanks,
   Owen

**Comment by thanhdowisc** [comment]
Thanks for the info, Owen. I'll look around for CI build infrastructure that supports windows.

**Pull request closed without merging**
