### PR TITLE
C++09withtest - enable test in c++09

### PR DESCRIPTION
**Pull request by thanhdowisc**
Hi Owen and Aliaksei,

I have ported the test portion to so that it now can build successfully in C++09 branch. Can you guy take a look and merge accordingly?

Thanks,
Thanh

### CODE REVIEW

**Comment by thanhdowisc** [comment]
This pull request results in 1 test failed in gcc and a compilation error with clang. Any insight for the root cause?

**Comment by asandryh** [comment]
Test error (https://travis-ci.org/hortonworks/orc/jobs/51749057):

/home/travis/build/hortonworks/orc/test/TestCompression.cc:448: Failure
Value of: length
Actual: 3
Expected: 30
[ FAILED ] Zlib.testInflateSequence (0 ms)

clang compile errors:
https://travis-ci.org/hortonworks/orc/jobs/51749058


On 02/22/2015 02:47 PM, Thanh Do wrote:

This pull request results in 1 test failed in gcc and a compilation error with clang. Any insight for the root cause?

�

**Comment by thanhdowisc** [comment]
OK, I'll take a look and update the branch

**Comment by thanhdowisc** [comment]
Hi Aliaksei,

I checked out the bare C++09 and try to build it in my Mac but got following errors:

usr/local/include/google/protobuf/stubs/common.h:199:32: error: 'long long' is a
      C++11 extension [-Werror,-Wc++11-long-long]
static const int64 kint64max = GOOGLE_LONGLONG(0x7FFFFFFFFFFFFFFF);
                               ^
/usr/local/include/google/protobuf/stubs/common.h:192:28: note: expanded from
      macro 'GOOGLE_LONGLONG'
#define GOOGLE_LONGLONG(x) x##LL
                           ^
<scratch space>:36:1: note: expanded from here

[any many more error like this followed]

The command I use to build:

mkdir build
cd build
cmake .. -DC09=true
make


Do you have any idea what cause the error?

**Comment by thanhdowisc** [comment]
Hi Owen, is this ready to merge?

**Comment by thanhdowisc** [comment]
Hi guys, I plan to merge this to c++09 and enable testing in appveyor. Can I go for it?

**Pull request merged**
